- .github/workflows/deploy_base.yaml
- .github/workflows/manual-deploy.yaml
GHA workflow for deploying Odin to dev.
Broken into two files, a deploy-base, which will allow for parallel deploy of future odin-esq applications. And the `manual-deploy` which calls `deploy-base` with required inputs. 
In the future this will be adjusted to allow for deploy to prod, along with automated deploys based on PR merge and/or application versioning.
> FEAT: Manually Deploy Odin to Dev

- src/odin/generate/cubic/ods_fact.py
- src/odin/ingestion/qlik/cubic_archive.py
- src/odin/job.py
- src/odin/run.py
- src/odin/utils/aws/s3.py
- src/odin/utils/parquet.py
- src/odin/utils/runtime.py
- tests/job_test.py
Constructing jobs as python Class objects seems to cause an issue with clearing resources between job runs. I believe this is related to the long-lived classes hanging on to resources after a job has completed. 
To resolve this issue, this change runs each OdinJob inside of a process using the `job_proc_schedule` function as the `sched.scheduler` callback. 
This change was deployed to Dev yesterday evening and resulted the the following change to memory usage:
As can be seen, memory usage between job runs now drops to almost 0.
> FIX: run each Job in Process to free resources

- src/odin/generate/cubic/ods_fact.py
- src/odin/ingestion/qlik/cubic_archive.py
- src/odin/utils/parquet.py
- tests/utils/parquet_test.py
The `pyarrow.acero` based `ds_column_min_max` function was becoming slow on very large PROD ODS datasets. 
This change adds a parquet dataset min_max function based on the dataset metadata. It only pulls file metadata so is very fast for very large parquet datasets. This will only work if the dataset has statistics written to the parquet file, which all ODIN parquet files do. 
For the `cubic_qlik/EDW.DEVICE_EVENT` dataset, which is about 10GB in size (~319,810,572 rows):
```
%timeit -n 5 -r 5  ds_metadata_min_max(ds, "header__change_seq")
%timeit -n 1 -r 1  ds_column_min_max(ds, "header__change_seq")
```
> [FEAT] New parquet dataset min_max function based on dataset metadata

- src/odin/run.py
- src/odin/utils/logger.py
- src/odin/utils/runtime.py
- tests/utils/runtime_test.py
Asana Task: [Make Odin more configurable](https://app.asana.com/0/1209584755824899/1209886680141188/f)
I'm planning to refactor how config is specified. That will be easier if there are fewer things that need to be configured between different environments. So this removes configurability for a couple things that don't need it.
No changes in prod. Minor changes when developing locally.
- Always set the number of threads is 2x the number of cpus.
- This was already the case in AWS.
- This doubles the number of threads when not running in AWS.
- Remove timestamp from local logging.
- It was already not used in AWS.
- This is a change when not running locally, but the timestamp isn't really that useful anyway and kind of noisy.
- Remove the SERVICE_NAME env var
- It was set in the app and …
> remove unneeded configurability

- src/odin/ingestion/qlik/cubic_archive.py
- src/odin/ingestion/qlik/utils.py
Noticed while doing #11 ([comment](https://github.com/mbta/odin/pull/11#discussion_r2033489255)), but was removed from that PR.
This looks like an unintentional typo, setting `save_local` to the default value `bool` instead of it being a type annotation. I believe the effect would be that in AWS, the `save_local` path (utils.py line 88) would always be taken, because the value `bool` is truthy. After this change, that path would no longer be taken.
> fix: pass save_local to find_qlik_load_files

- src/odin/job.py
- tests/job_test.py
This change modified how OdinJob's are run, using a Multiprocessing Process instead of a Pool. 
The Pool construct would hang if a process, started by the Pool, was killed by the kernel because of something like an OOM error. The Process construct returns gracefully in this situation, providing a non-zero exitcode to indicate what happened to the child process. 
The Process construct does not offer simple return values like the Pool does. So this change also implements a process-safe shared Value object, to return `run_delay_secs` from the OdinJob.start function.
> FEAT: Run OdinJob in Process instead of Pool

- src/odin/utils/parquet.py
- tests/utils/parquet_test.py
This change adds a new `ds_metadata_limit_k_sorted` function to pull records from large parquet datasets in a more performant manner in some situations.
> FEAT: New ds_metadata_limit_k_sorted function for parquet

- src/odin/ingestion/qlik/clean.py
- src/odin/ingestion/qlik/cubic_archive.py
This reverts the removal of the `clean_old_snapshots` process scheduling the Cubic Archive job.
The `clean_old_snapshots` process is still needed when adding new tables for processing. It will ensure that only the most recent snapshot is Archived for newly added Cubic tables.
> FIX: Add back qlik snapshot clean process

- .env.template
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- src/odin/ingestion/afc/afc_archive.py
- src/odin/job.py
- src/odin/run.py
- src/odin/utils/locations.py
- src/odin/utils/runtime.py
This is an initial implementation for the S&B AFC API Archive job. 
The API, as it currently stands, has no functional pagination method, so this should not be deployed to PROD. 
The API works by providing csv.gz files as downloadable blobs. This Job downloads those blobs, converts them to parquet and then merges the parquet with any existing parquet files in S3. 
This implementation also does not do any file path partitioning. Not totally sure if this will or will not be needed in the future. 
This is in conjunction with a devops PR: https://github.com/mbta/devops/pull/2745 that made the required secrets available to the ECS in AWS.
> FEAT: DEV Pipeline for S&B AFC API Archive Job

- src/odin/job.py
- src/odin/utils/runtime.py
Reverting the addition of the `delete_folder_contens` (spelling) function.
This change resulted in some kind of race condition with the regular `/tmp` folder cleanup process. Shelving this idea for now, but need to re-visit if a specific job failure mode causes disk space issues.
> FIX: Drop manual /tmp folde cleanup in all Jobs

- src/odin/ingestion/afc/afc_archive.py
- src/odin/migrate/migrations/odin-dev/0002.py
- src/odin/migrate/migrations/odin-prod/0002.py
- tests/ingestion/afc/afc_archive_test.py
This change fixes the logic used for the `load_sids` method of the `ArchiveAFCAPI` Job. 
After deployment to PROD it was identified that incremental data loading was not occurring as expected. This change fixes the incremental loading logic of `load_sids` and also adds tests to ensure proper functioning of the method. 
To reset the S&B API datasest this change includes a migration that will delete all existing API data. Additional devops permissions are required to execute this migration. 
terraform_modules PR: https://github.com/mbta/terraform_modules/pull/209
devops PR: https://github.com/mbta/devops/pull/2858
> FIX: S&B API load_sids logic

- src/odin/ingestion/afc/afc_archive.py
- tests/ingestion/afc/afc_archive_test.py
The S&B AFC API `count` endpoint has been fixed to always return a limited number of results.
This changed has allowed a full featured pagination implementation for pulling data from the API.
The partial pagination solution has been removed from this process and the archive process now assumes that full pagination is always possible.
> feat: AFC API `count` endpoint fixed.

- src/odin/migrate/process.py
This change updates the migration process to delete the old migration file before uploading a new one.
The migration folders for dev and prod both currently have 2 files in them, which needs to be fixed before this change is deployed.
Infra Request to delete PROD object: https://app.asana.com/1/15492006741476/project/1113179098808463/task/1210235954328612
> fix: Delete old files during migration

- src/odin/ingestion/afc/afc_archive.py
- tests/ingestion/afc/afc_archive_test.py
This change updates the AFC API download process to verify all files received from the API.
This verification will compare results from the `count` endpoint to data in the csv returned from the `stagetable` endpoint.
Data received from the `count` endpoint is in the following format:
```
[
{"jobId": 1, "dataCount": 10},
{"jobId": 2, "dataCount": 5},
{"jobId": 3, "dataCount": 12},
]
```
In this data `jobId==sid`. We will compare this `count` data to a `group_by` aggregation on the `sid` column of the csv files received and check for:
1. sid(s) in csv file that are not in `count` results.
2. sid(s) in `count` results that are not in csv file.
3. equal record counts in csv file and `dataCount` values from API
> feat: Verify AFC API Downloads

- src/odin/ingestion/afc/afc_archive.py
This change updates the `.download_csv()` method of ArchiveAFCAPI class to correctly stream the file to disk.
Previous implementation was still reading entire response into memory so it could be uncompressed and written to csv file in one step.
Updated process first streams the csv.gz download to a gz file, and then uncompresses the .gz file to .csv in a seperate step.
This should resolve all memory issues associated with downloading potentially large csv.gz files.
> fix: AFC API File Download Stream

- src/odin/ingestion/afc/afc_archive.py
- tests/ingestion/afc/afc_archive_test.py
This change updates the ArchiveAFCAPI Job to handle changes to the response structure of the `tableinfos` endpoint of the AFC API.
The API now returns a list of single element dictionaries with the schema of APITableInfo.
```
[
{
"v_card": {
"type": "static",
"frequency": "PT24H",
"remarks": "Legacy: Each single (physical) card within the system has one entry in this table.",
"table_infos": [
...
]
}
},
{
"v_deviceclass": {
"type": "static",
"frequency": "PT24H",
"remarks": "Deviceclass table is mandatory and contains information about the device classification",
"table_infos": [
{
"column_name": "sid",
"ordinal_position": 1,
"is_nullable": "YES",
"data_type": "bigint",
"max_length": 64,
"default_value": null,
"remarks": null
}
...
```
> fix: S&B AFC API tableinfos schema change

- src/odin/ingestion/afc/afc_archive.py
- src/odin/utils/aws/s3.py
- tests/ingestion/afc/afc_archive_test.py
S&B API is now providing a `type` value from the `tableinfos` endpoint.
The `type` can either be "static" or "transactional".
"static" indicates the table should only ever have 1 sid/jobId value at a time and performs a full truncate and reload for any new data.
"transactional" is an incremental (append-only) data loading strategy.
The `ArchiveAFCAPI` Job previously assumed all tables operated as "transactional" this change updates the process to also handle "static" table types.
> feat: process seperate S&B AFC API table types

- src/odin/generate/cubic/ods_fact.py
- src/odin/generate/data_dictionary/cubic_reports_sql.py
- src/odin/migrate/migrations/odin-dev/0003.py
- src/odin/migrate/migrations/odin-prod/0003.py
This change updates the ODS Fact table generation process to explicitly drop all unwanted "history" columns before creating fact parquet files.
The history columns being dropped are:
- header__year
- header__month
- header__change_oper
- header__timestamp
- header__from_csv
- snapshot
These columns were previously being dropped for all "Insert" records, however they were not being dropped for "Update" records causing the columns to be inserted on UPDATE operations.
Along with fixing the Cubic Fact process to drop these columns correctly, this change also includes migrations to remove these columns from all existing Cubic ODS Fact parquet files.
> fix: drop history columns from cubic fact files

- src/odin/generate/cubic/ods_fact.py
- src/odin/generate/data_dictionary/duck_db.py
- src/odin/ingestion/afc/afc_archive.py
- src/odin/migrate/migrations/odin-prod/0004.py
- tests/ingestion/afc/afc_archive_test.py
This change implements changes to the S&B AFC API endpoints, which include the following:
- `sid` column name changed to `job_id`
- `identity_value` column added to all datasets
- endpoint parameter names changed from `sidFrom` -> `jobIdFrom` & `sidTo` -> `jobIdTo`
This change also updates the default ingestion format from csv to ndjson files.
Fix .drop call in Ods Fact job to not error if some columns are not available to drop.
> feat: S&B updated API endpoints

- src/odin/ingestion/afc/afc_archive.py
- tests/ingestion/afc/afc_archive_test.py
This change modifies the way job_id's are pulled from the S&B AFC API /count endpoint. 
Previously, each Job instance pulled 1000 job_id's per run. The new implementation will continue to pull job_ids as a generator until the hard disk is filled up or there are no more job_ids to pull.
> feat: pull job_id's from /count endpoint as generator

- src/odin/ingestion/qlik/cubic_archive.py
- tests/utils/parquet_test.py
This change is attempting to fix OOM errors being thowing by the ArchiveCubicQlikTable process for the TRANSACTION_HISTORY table.
This will stop generating CDC parquet files if a memory threshold is reached. This threshold should be reviewed in the future to confirm it had no negative effects on other parts of the pipeline.
Asana Task: https://app.asana.com/1/15492006741476/project/1208949713596462/task/1210654078793430
> fix: TRANSACTION_HISTORY Archive OOM

- src/odin/ingestion/afc/afc_archive.py
This change adds the `v_eventtext` table to the S&B AFC Archive job. This table was add to the API today at the request of the MBTA finance team.
> chore: Add s&b v_eventtext table

- src/odin/generate/cubic/ods_fact.py
- src/odin/utils/parquet.py
- tests/utils/parquet_test.py
For the last few days, Odin has been throwing OOM errors when attempting to process the EDW.TRANSACTION_HISTORY table for the ODSFACT job.
This error was traced back to the `ds_batched_join` function, which is designed to join a polars dataframe to a very large parquet dataset in a memory constrained environment. Unfortunately, the implementation was not as memory constrained as originally thought.
In this instance, the JOIN operations was matching to a very small number of records from almost every partition across the whole dataset. In converting a pyarrow RecordBatch to a polars Dataframe, for each JOIN match, the memory allocation from each matched RecordBatch was being leaked as the dataset was iterated through.
This conversion to Polars is only required for JOIN operations on key …
> fix: ODSFact TRANSACTION_HISTORY OOM

- src/odin/migrate/migrations/odin-dev/0008.py
- src/odin/migrate/migrations/odin-prod/0009.py
- src/odin/utils/aws/s3.py
- src/odin/utils/locations.py
This change updates/standardizes some ODIN dataset paths. When these paths were originally created, the selected paths were not fully discussed/planned.
After a review of all existing dataset paths the attached changes were selected.
These changes will be executed via S3 migration, after the migration the ODIN application should continue operating without interruption. Will be tested on DEV before deploy to PROD.
Asana task: https://app.asana.com/1/15492006741476/project/1208949713596457/task/1210413896483727
> feat: update ODIN DATA paths
